serial:
# port: /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_7543331373935161D021-if00
  port: /dev/arduino
  baud: 9600
  timeout: 10
  
mqtt:
  host: 192.168.1.5
  port: 1883
  ssl: {}
  clientid: pyserialgw